dist: bionic
language: R
cache: packages
warnings_are_errors: true

compiler:
  - gcc
os:
  - linux

r_build_args: "--no-build-vignettes --resave-data --no-manual"
r_check_args: "--no-build-vignettes --resave-data --no-manual --as-cran"

before_install:
  - sudo apt-get -y install libudunits2-dev
  - sudo apt-get -y install libgdal-dev
  - sudo apt-get -y install xorg
  - sudo apt-get -y install libx11-dev
  - sudo apt-get -y install libglu1-mesa-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
