dist: bionic
language: R
cache: packages
warnings_are_errors: false

compiler:
  - gcc
os:
  - linux

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes"

before_install:
  - sudo apt-get -y install libudunits2-dev
  - sudo apt-get -y install libgdal-dev
  - sudo apt-get -y install xorg
  - sudo apt-get -y install libx11-dev
  - sudo apt-get -y install libglu1-mesa-dev
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)'

after_success:
  - Rscript -e 'library(covr); codecov()'
