# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
warnings_are_errors: false

jobs:
  include:
    - os: linux
      dist: bionic

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes"

before_install:
  - sudo apt-get -y install libudunits2-dev
  - sudo apt-get -y install libgdal-dev
  - Rscript -e 'install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)'

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'INLA:::inla.dynload.workaround()'
