# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes"

before_install:
  - sudo apt-get -y install libudunits2-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
