# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

cache:
  - C:\RLibrary

platform:
  - x64

# Adapt as necessary starting from here
environment:
  global:
    R_BUILD_ARGS: --no-build-vignettes --resave-data --no-manual
    R_CHECK_ARGS: --no-build-vignettes --resave-data --no-manual --as-cran
    WARNINGS_ARE_ERRORS: true
    _R_CHECK_FORCE_SUGGESTS_: true
    USE_RTOOLS: true ## to be able to use Remotes (i.e. packages from non-CRAN sources)

  matrix:
    - R_VERSION: 4.2.0
      R_ARCH: x64

    - R_VERSION: 3.6.3
      R_ARCH: i386

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
